namespace MqttProbe.Models.Mqtt;

public sealed class Connection : IEquatable<Connection>
{
    private const string Bluegrassiot = "mqttprobe_";

    public Guid Id { get; init; } = Guid.NewGuid();
    public string Name { get; set; } = "New Connection";
    public string? Host { get; set; }
    public int Port { get; set; } = 1883;
    public string? User { get; set; }
    public string? Password { get; set; }
    public Protocol Protocol { get; set; } = Protocol.Mqtt;
    public MqttVersion MqttVersion { get; set; } = MqttVersion.V311;
    public string ClientId { get; set; } = GetAutoGeneratedClientId();
    public string WebsocketBasePath { get; set; } = "mqtt";

    public bool UseTls { get; set; }
    public bool AllowUntrustedCertificate { get; set; }
    public int ConnectTimeout { get; set; } = 15;
    public List<string> SubscribedTopics { get; set; } = [];

    public Connection CloneWithoutPassword()
    {
        var clone = Clone();
        clone.Password = null;
        return clone;
    }

    public Connection Clone() => (Connection)MemberwiseClone();

    private static string GetAutoGeneratedClientId() => Bluegrassiot + Guid.NewGuid();

    public bool Equals(Connection? other)
    {
        if (other is null)
            return false;

        return Name == other.Name &&
               Host == other.Host &&
               Port == other.Port &&
               User == other.User &&
               Password == other.Password &&
               Protocol == other.Protocol &&
               MqttVersion == other.MqttVersion &&
               ClientId == other.ClientId &&
               UseTls == other.UseTls &&
               AllowUntrustedCertificate == other.AllowUntrustedCertificate &&
               ConnectTimeout == other.ConnectTimeout &&
               WebsocketBasePath == other.WebsocketBasePath;
    }

    public override bool Equals(object? obj) => Equals(obj as Connection);

    public override int GetHashCode()
    {
        var hash = new HashCode();
        hash.Add(Name);
        hash.Add(Host);
        hash.Add(Port);
        hash.Add(User);
        hash.Add(Password);
        hash.Add(Protocol);
        hash.Add(MqttVersion);
        hash.Add(ClientId);
        hash.Add(UseTls);
        hash.Add(AllowUntrustedCertificate);
        hash.Add(ConnectTimeout);
        hash.Add(WebsocketBasePath);
        return hash.ToHashCode();
    }
}

public enum Protocol
{
    Mqtt,
    WebSocket
}

public enum MqttVersion
{
    V311,
    V5
}
