using System.Diagnostics.CodeAnalysis;

namespace MqttProbe.Core.Models.Mqtt;

public sealed class Connection : IEquatable<Connection>
{
    private const string Bluegrassiot = "mqttprobe_";

    public Guid Id { get; init; } = Guid.NewGuid();
    public string Name { get; set; } = "New Connection";
    public string? Host { get; set; }
    public int Port { get; set; } = 1883;
    public string? User { get; set; }
    public string? Password { get; set; }
    public Protocol Protocol { get; set; } = Protocol.Mqtt;
    public MqttVersion MqttVersion { get; set; } = MqttVersion.V311;
    public string ClientId { get; set; } = GetAutoGeneratedClientId();
    public string WebsocketBasePath { get; set; } = "mqtt";

    public bool UseTls { get; set; }
    public bool AllowUntrustedCertificate { get; set; }
    public string? ClientCertificateAssetId { get; set; }
    public int ConnectTimeout { get; set; } = 15;
    public int ReconnectDelay { get; set; } = 5;
    public int KeepAlivePeriod { get; set; } = 15;
    public bool CleanStart { get; set; } = true;
    public uint SessionExpiryIntervalSeconds { get; set; } = 3600;
    [System.Text.Json.Serialization.JsonConverter(typeof(SubscribedTopicsJsonConverter))]
    public List<SubscribedTopic> SubscribedTopics { get; set; } = [];
    public List<string> TopicExcludes { get; set; } = [];

    public Connection CloneWithoutPassword()
    {
        var clone = Clone();
        clone.Password = null;
        return clone;
    }

    public Connection Clone()
    {
        var clone = (Connection)MemberwiseClone();
        clone.SubscribedTopics = SubscribedTopics
            .Select(t => new SubscribedTopic
            {
                Topic = t.Topic,
                QualityOfServiceLevel = t.QualityOfServiceLevel
            })
            .ToList();
        clone.TopicExcludes = [.. TopicExcludes];
        return clone;
    }

    private static string GetAutoGeneratedClientId() => Bluegrassiot + Guid.NewGuid();

    public bool Equals(Connection? other)
    {
        if (other is null)
            return false;

        return Name == other.Name &&
               Host == other.Host &&
               Port == other.Port &&
               User == other.User &&
               Password == other.Password &&
               Protocol == other.Protocol &&
               MqttVersion == other.MqttVersion &&
               ClientId == other.ClientId &&
               UseTls == other.UseTls &&
               AllowUntrustedCertificate == other.AllowUntrustedCertificate &&
               ConnectTimeout == other.ConnectTimeout &&
               ReconnectDelay == other.ReconnectDelay &&
               KeepAlivePeriod == other.KeepAlivePeriod &&
               WebsocketBasePath == other.WebsocketBasePath &&
               ClientCertificateAssetId == other.ClientCertificateAssetId &&
               CleanStart == other.CleanStart &&
               SessionExpiryIntervalSeconds == other.SessionExpiryIntervalSeconds &&
               TopicExcludes.SequenceEqual(other.TopicExcludes, StringComparer.Ordinal);
    }

    public override bool Equals(object? obj) => Equals(obj as Connection);

    [SuppressMessage("ReSharper", "NonReadonlyMemberInGetHashCode")]
    public override int GetHashCode()
    {
        var hash = new HashCode();
        hash.Add(Name, StringComparer.Ordinal);
        hash.Add(Host, StringComparer.Ordinal);
        hash.Add(Port);
        hash.Add(User, StringComparer.Ordinal);
        hash.Add(Password, StringComparer.Ordinal);
        hash.Add(Protocol);
        hash.Add(MqttVersion);
        hash.Add(ClientId, StringComparer.Ordinal);
        hash.Add(UseTls);
        hash.Add(AllowUntrustedCertificate);
        hash.Add(ConnectTimeout);
        hash.Add(ReconnectDelay);
        hash.Add(KeepAlivePeriod);
        hash.Add(WebsocketBasePath, StringComparer.Ordinal);
        hash.Add(ClientCertificateAssetId, StringComparer.Ordinal);
        hash.Add(CleanStart);
        hash.Add(SessionExpiryIntervalSeconds);
        foreach (var topic in TopicExcludes)
            hash.Add(topic, StringComparer.Ordinal);
        return hash.ToHashCode();
    }
}

public enum Protocol
{
    Mqtt,
    WebSocket
}

public enum MqttVersion
{
    V311,
    V5
}
